CREATE TABLE IF NOT EXISTS `inward_register` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unique_id` varchar(50) NOT NULL,
  `issue_no` varchar(100) NOT NULL,
  `issue_date` date NOT NULL,
  `letter_name` varchar(255) NOT NULL,
  `letter_received_date` date NOT NULL,
  `from_whom_received` text NOT NULL,
  `received_letter_description` text NOT NULL,
  `received_letter_number` varchar(100),
  `received_letter_date` date,
  `received_letter_attachment` varchar(100),
  `reply_to_number` varchar(100),
  `reply_to_date` date,
  `our_reply_number` varchar(100),
  `our_reply_date` date,
  `forwarded_letter_number` varchar(100),
  `forwarded_letter_date` date,
  `subject` text NOT NULL,
  `file_number` varchar(100),
  `section` varchar(100),
  `signed_date` date,
  `sent_to` varchar(255),
  `remarks` text,
  `created_by` int(11),
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int(11),
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_id` (`unique_id`),
  KEY `issue_date` (`issue_date`),
  KEY `letter_received_date` (`letter_received_date`),
  KEY `created_by` (`created_by`),
  KEY `is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
