-- MP Vidhan Sabha Member table creation script
CREATE TABLE IF NOT EXISTS `mp_vidhan_sabha_member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `month` varchar(50),
  `date` date,
  `block_id` int(11),
  `panchayat_id` int(11),
  `lok_sabha_id` int(11),
  `vidhan_sabha_id` int(11),
  `district_id` int(11),
  `village_id` int(11),
  `name` varchar(255) NOT NULL,
  `position` varchar(100),
  `mobile_no` varchar(20),
  `bg` varchar(50),
  `bc` varchar(50),
  `er` varchar(50),
  `br` varchar(50),
  `ip` varchar(50),
  `sc` varchar(50),
  `sa` varchar(50),
  `yc` varchar(50),
  `ap` varchar(50),
  `fp` varchar(50),
  `pp` varchar(50),
  `wc` varchar(50),
  `pa` varchar(50),
  `pc` varchar(50),
  `ak` varchar(50),
  `fm` varchar(50),
  `zp` varchar(50),
  `vp` varchar(50),
  `sr` varchar(50),
  `in_field` varchar(50),
  `eo` varchar(50),
  `gs` varchar(50),
  `us` varchar(50),
  `pw` varchar(50),
  `nl` varchar(50),
  `fr` varchar(50),
  `so` varchar(50),
  `st` varchar(50),
  `ob` varchar(50),
  `smw` varchar(50),
  `smtw` varchar(50),
  `it` varchar(50),
  `test` varchar(50),
  `dyc` varchar(50),
  `dcc` varchar(50),
  `obc` varchar(50),
  `cell` varchar(50),
  `mp` varchar(50),
  `dt` varchar(50),
  `dp` varchar(50),
  `avp` varchar(50),
  `meet` varchar(50),
  `media` varchar(50),
  `mla_x_mla` varchar(50),
  `vech` varchar(50),
  `it_cell_exp` varchar(50),
  `info` varchar(50),
  `nsui` varchar(50),
  `imp` varchar(50),
  `advise` varchar(50),
  `ref` varchar(50),
  `remark` text,
  `created_by` int(11) NOT NULL,
  `added_by` int(11) NOT NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `added_by` (`added_by`),
  KEY `district_id` (`district_id`),
  KEY `block_id` (`block_id`),
  KEY `panchayat_id` (`panchayat_id`),
  KEY `vidhan_sabha_id` (`vidhan_sabha_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
