-- US Code Table
CREATE TABLE IF NOT EXISTS `us_code` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(100) NOT NULL UNIQUE,
  `description` varchar(255),
  `status` tinyint(1) DEFAULT 1,
  `created_by` int(11),
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int(11),
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default codes
INSERT INTO `us_code` (`code`, `description`, `status`) VALUES
('SC', 'SC', 1),
('YC', 'YC', 1),
('WC', 'WC', 1),
('PA', 'PA', 1),
('SM', 'SM', 1),
('EO', 'EO', 1),
('GS', 'GS', 1),
('DCC', 'DCC', 1),
('PW', 'PW', 1),
('NL', 'NL', 1),
('FR', 'FR', 1),
('SO', 'SO', 1),
('ST', 'ST', 1),
('REF', 'REF', 1),
('US', 'US', 1),
('SMW', 'SMW', 1),
('DYC', 'DYC', 1),
('OBC', 'OBC', 1),
('DT', 'DT', 1),
('DP', 'DP', 1),
('MLA', 'MLA', 1),
('AVP', 'AVP', 1),
('MEET', 'MEET', 1),
('MEDIA', 'MEDIA', 1),
('X MLA', 'X MLA', 1),
('BC (बूथ कमेटी)', 'BC (बूथ कमेटी)', 1),
('PP (पेज प्रभारी)', 'PP (पेज प्रभारी)', 1),
('IP (प्रभावशाली व्यक्ति)', 'IP (प्रभावशाली व्यक्ति)', 1),
('FH (परिवार का मुखिया)', 'FH (परिवार का मुखिया)', 1),
('SMM (सोशल मीडिया मित्र)', 'SMM (सोशल मीडिया मित्र)', 1),
('MS (महिला समिति)', 'MS (महिला समिति)', 1),
('FP (फलिया प्रभारी)', 'FP (फलिया प्रभारी)', 1),
('ER (चुनाव प्रभारी)', 'ER (चुनाव प्रभारी)', 1),
('वरिष्ठ', 'वरिष्ठ', 1),
('युवा', 'युवा', 1),
('वोटरप्रभारी(१० घर)', 'वोटरप्रभारी(१० घर)', 1),
('BLA (बूथ लेवल एजेंट)', 'BLA (बूथ लेवल एजेंट)', 1);
