import * as Yup from "yup";
import { IEventFormValues } from "@app/types/event";
export type { IEventFormValues };

export const eventSchema = Yup.object().shape({
  uniqueId: Yup.string().optional(),
  district: Yup.string().required("District is required"),
  otherDistrictName: Yup.string().when('district', {
    is: 'other',
    then: (schema) => schema.required('Please specify the district name'),
    otherwise: (schema) => schema.optional()
  }),
  year: Yup.string().required("Year is required"),
  month: Yup.string().required("Month is required"),
  receivingDate: Yup.date().required("Receiving Date is required"),
  programDate: Yup.date().required("Program Date is required"),
  time: Yup.string().required("Time is required"),
  eventType: Yup.string().required("Event Type is required"),
  eventDetails: Yup.string().required("Event Details is required"),
  priority: Yup.string().required("Priority is required"),
  venueCity: Yup.string().required("Venue City is required"),
  referencePerson: Yup.string().required("Reference Person is required"),
  contactNumber: Yup.string().required("Contact Number is required"),
  address: Yup.string().required("Address is required"),
  name: Yup.string().required("Name is required"),
  location: Yup.string().required("Location is required"),
  probability: Yup.string().required("Probability is required"),
  duration: Yup.string().required("Duration is required"),
  attended: Yup.string(),
  pressConference: Yup.string(),
  dispatchDate: Yup.string().nullable(),
  dispatchNumber: Yup.string().nullable(),
  remarks: Yup.string(),
  addedBy: Yup.string(),
  block: Yup.string().nullable(),
  office: Yup.string().nullable(),
});

export const eventInitialValues: IEventFormValues = {
  uniqueId: "",
  district: "",
  otherDistrictName: "",
  year: "",
  month: "",
  receivingDate: "",
  programDate: "",
  time: "",
  eventType: "",
  eventDetails: "",
  priority: "Medium",
  venueCity: "",
  referencePerson: "",
  contactNumber: "",
  address: "",
  name: "",
  location: "",
  probability: "",
  duration: "",
  attended: "No",
  pressConference: "No",
  dispatchDate: "",
  dispatchNumber: "",
  remarks: "",
  addedBy: "",
  block: "",
  office: "",
};
