import * as Yup from "yup";
import { IMemberFormValues } from "@app/types/member";
export type { IMemberFormValues };

const emptyStringToNull = (value: any, originalValue: any) => {
  if (typeof originalValue === "string" && originalValue === "") {
    return null;
  }
  return value;
};

export const memberSchema = Yup.object().shape({
  name: Yup.string().required("Name is required"),
  voterId: Yup.string().optional(),
  mobile: Yup.string()
    .matches(/^[0-9]{10}$/, "Must be exactly 10 digits")
    .optional(),
  mobileNo: Yup.string()
    .matches(/^[0-9]{10}$/, "Must be exactly 10 digits")
    .optional(),
  fatherName: Yup.string().optional(),
  dob: Yup.string().optional(),
  dom: Yup.string().optional(),
  district: Yup.string().optional(),
  block: Yup.string().optional(),
  boothName: Yup.string().optional(),
  boothNumber: Yup.string().optional(),
  grampanchayat: Yup.string().optional(),
  village: Yup.string().optional(),
  samiti: Yup.string().optional(),
  toll: Yup.string().optional(),
  jaati: Yup.string().optional(),
  age: Yup.number().optional(),
  education: Yup.string().optional(),
  address: Yup.string().optional(),
  gender: Yup.string().optional(),
  vehicle: Yup.string().optional(),
  group: Yup.string().optional(),
  govtEmployee: Yup.string().optional(),
  party: Yup.string().optional(),
  postYear: Yup.number().optional(),
  code: Yup.string().optional(),
  nariSammanYojna: Yup.string().optional(),
  farmerLoanWaiver: Yup.string().optional(),
  reference: Yup.string().optional(),
  remark: Yup.string().optional(),
  facebook: Yup.string().optional(),
  instagram: Yup.string().optional(),
  twitter: Yup.string().optional(),
  startLat: Yup.number().optional(),
  startLong: Yup.number().optional(),
  startDate: Yup.string().optional(),
  endLat: Yup.number().optional(),
  endLong: Yup.number().optional(),
  endDate: Yup.string().optional(),
  image: Yup.string().optional(),
  vidhansabha: Yup.string().optional(),
  memberType: Yup.string().optional(),
  panchayat: Yup.string().optional(),
  janpadPanchayat: Yup.string().optional(),
  mandalam: Yup.string().optional(),
  position: Yup.string().optional(),
  lokSabha: Yup.string().optional(),
  year: Yup.string().optional(),
  month: Yup.string().optional(),
  date: Yup.string().optional(),
  additionalCode: Yup.array().optional(),
  
  // 50 Boolean Roles
  bg: Yup.boolean().optional(),
  bc: Yup.boolean().optional(),
  er: Yup.boolean().optional(),
  br: Yup.boolean().optional(),
  ip: Yup.boolean().optional(),
  sc: Yup.boolean().optional(),
  sa: Yup.boolean().optional(),
  yc: Yup.boolean().optional(),
  ap: Yup.boolean().optional(),
  fp: Yup.boolean().optional(),
  pp: Yup.boolean().optional(),
  wc: Yup.boolean().optional(),
  pa: Yup.boolean().optional(),
  pc: Yup.boolean().optional(),
  ak: Yup.boolean().optional(),
  fm: Yup.boolean().optional(),
  zp: Yup.boolean().optional(),
  vp: Yup.boolean().optional(),
  sr: Yup.boolean().optional(),
  in_field: Yup.boolean().optional(),
  eo: Yup.boolean().optional(),
  gs: Yup.boolean().optional(),
  us: Yup.boolean().optional(),
  pw: Yup.boolean().optional(),
  nl: Yup.boolean().optional(),
  fr: Yup.boolean().optional(),
  so: Yup.boolean().optional(),
  st: Yup.boolean().optional(),
  ob: Yup.boolean().optional(),
  smw: Yup.boolean().optional(),
  smtw: Yup.boolean().optional(),
  it: Yup.boolean().optional(),
  test: Yup.boolean().optional(),
  dyc: Yup.boolean().optional(),
  dcc: Yup.boolean().optional(),
  obc: Yup.boolean().optional(),
  cell_mp: Yup.boolean().optional(),
  dt: Yup.boolean().optional(),
  dp: Yup.boolean().optional(),
  avp: Yup.boolean().optional(),
  meet: Yup.boolean().optional(),
  media: Yup.boolean().optional(),
  mla_x_mla: Yup.boolean().optional(),
  vech: Yup.boolean().optional(),
  it_cell_exp: Yup.boolean().optional(),
  info: Yup.boolean().optional(),
  nsui: Yup.boolean().optional(),
  imp: Yup.boolean().optional(),
  advise: Yup.boolean().optional(),
  ref_code: Yup.boolean().optional(),
});

export const memberInitialValues: IMemberFormValues = {
  name: "",
  voterId: "",
  mobile: "",
  mobileNo: "",
  fatherName: "",
  dob: "",
  dom: "",
  district: "",
  block: "",
  boothName: "",
  boothNumber: "",
  grampanchayat: "",
  village: "",
  samiti: "",
  toll: "",
  jaati: "",
  age: 0,
  education: "",
  address: "",
  gender: "",
  vehicle: "",
  group: "",
  govtEmployee: "",
  party: "",
  postYear: 0,
  code: "",
  nariSammanYojna: "",
  farmerLoanWaiver: "",
  reference: "",
  remark: "",
  facebook: "",
  instagram: "",
  twitter: "",
  startLat: 0,
  startLong: 0,
  startDate: "",
  endLat: 0,
  endLong: 0,
  endDate: "",
  image: "",
  vidhansabha: "",
  memberType: "",
  panchayat: "",
  janpadPanchayat: "",
  mandalam: "",
  position: "",
  lokSabha: "",
  year: "",
  month: "",
  date: "",
  additionalCode: [],
  
  // 50 Boolean Roles
  bg: false,
  bc: false,
  er: false,
  br: false,
  ip: false,
  sc: false,
  sa: false,
  yc: false,
  ap: false,
  fp: false,
  pp: false,
  wc: false,
  pa: false,
  pc: false,
  ak: false,
  fm: false,
  zp: false,
  vp: false,
  sr: false,
  in_field: false,
  eo: false,
  gs: false,
  us: false,
  pw: false,
  nl: false,
  fr: false,
  so: false,
  st: false,
  ob: false,
  smw: false,
  smtw: false,
  it: false,
  test: false,
  dyc: false,
  dcc: false,
  obc: false,
  cell_mp: false,
  dt: false,
  dp: false,
  avp: false,
  meet: false,
  media: false,
  mla_x_mla: false,
  vech: false,
  it_cell_exp: false,
  info: false,
  nsui: false,
  imp: false,
  advise: false,
  ref_code: false,
};
