-- Create dispatch_register table
CREATE TABLE IF NOT EXISTS `dispatch_register` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL COMMENT 'Date field',
  `year` varchar(4) DEFAULT NULL COMMENT 'Year (2020-2028)',
  `month` varchar(20) DEFAULT NULL COMMENT 'Month name',
  `portal_no` varchar(100) DEFAULT NULL COMMENT 'Portal No.',
  `samiti_no` varchar(100) DEFAULT NULL COMMENT 'Samiti No.',
  `dispatch_no` varchar(100) DEFAULT NULL COMMENT 'Dispatch No.',
  `department_id` int(11) DEFAULT NULL COMMENT 'Department ID from department table',
  `particular_subject` text DEFAULT NULL COMMENT 'Particular (subject)',
  `reference` varchar(255) DEFAULT NULL COMMENT 'Reference',
  `block_id` int(11) DEFAULT NULL COMMENT 'Block ID from block table',
  `panchayat_id` int(11) DEFAULT NULL COMMENT 'Panchayat ID from panchayat table',
  `village_id` int(11) DEFAULT NULL COMMENT 'Village ID from village table',
  `created_by` int(11) NOT NULL COMMENT 'User who created the record',
  `created_at` datetime NOT NULL COMMENT 'Created timestamp',
  `updated_by` int(11) DEFAULT NULL COMMENT 'User who updated the record',
  `updated_at` datetime DEFAULT NULL COMMENT 'Updated timestamp',
  `isDeleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
  PRIMARY KEY (`id`),
  KEY `department_id` (`department_id`),
  KEY `block_id` (`block_id`),
  KEY `panchayat_id` (`panchayat_id`),
  KEY `village_id` (`village_id`),
  KEY `created_by` (`created_by`),
  KEY `year` (`year`),
  KEY `month` (`month`),
  KEY `isDeleted` (`isDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Dispatch Register table';
