import * as Yup from "yup";
import { IAssemblyIssueFormValues } from "@app/types/assemblyIssue";
export type { IAssemblyIssueFormValues };

export const assemblyIssueSchema = Yup.object().shape({
  uniqueId: Yup.string().optional(),
  sectorName: Yup.string().optional(),
  microSectorNo: Yup.string().optional(),
  microSectorName: Yup.string().optional(),
  year: Yup.string().required("Year is required"),
  month: Yup.string().optional(),
  date: Yup.string().optional(),
  district: Yup.string().optional(),
  assembly: Yup.string().optional(),
  acMpNo: Yup.string().optional(),
  block: Yup.string().required("Block is required"),
  recommendedLetterNo: Yup.string().optional(),
  boothName: Yup.string().optional(),
  boothNo: Yup.string().optional(),
  panchayatName: Yup.string().required("Panchayat is required"),
  village: Yup.string().required("Village is required"),
  majraFaliya: Yup.string().optional(),
  workProblem: Yup.string().required("Work/Problem is required"),
  office: Yup.string().optional(),
  approximateCost: Yup.number().min(0).optional(),
  department: Yup.string().required("Department is required"),
  priority: Yup.string().optional(),
  tsNoDate: Yup.string().optional(),
  asNoDate: Yup.string().optional(),
  typeOfWork: Yup.string().optional(),
  subWorkType: Yup.string().optional(),
  middleMen: Yup.string().optional(),
  middleManContact: Yup.string()
    .matches(/^[0-9]{10}$/, "Must be exactly 10 digits")
    .optional(),
  beneficiaryName: Yup.string().optional(),
  beneficiaryContact: Yup.string()
    .matches(/^[0-9]{10}$/, "Must be exactly 10 digits")
    .optional(),
  po: Yup.string().optional(),
  avedanFile: Yup.string().optional(),
  avedanFileName: Yup.string().optional(),
  accountDetails: Yup.string().optional(),
  adharCardNumber: Yup.string().optional(),
  ifscNumber: Yup.string().optional(),
  documentFile: Yup.string().optional(),
  documentFileName: Yup.string().optional(),
  remarkGoshana: Yup.string().optional(),
  remarkTipUsd: Yup.string().optional(),
  addedBy: Yup.string().optional(),
  latLng: Yup.string().optional(),
  registrationDate: Yup.string().optional(),
  totalMembers: Yup.number().optional(),
  status: Yup.string().optional(),
  issueType: Yup.string().optional(),
});

export const assemblyIssueInitialValues: IAssemblyIssueFormValues = {
  uniqueId: "",
  sectorName: "",
  microSectorNo: "",
  microSectorName: "",
  year: new Date().getFullYear().toString(),
  month: "",
  date: "",
  district: "",
  assembly: "",
  acMpNo: "N/A",
  block: "",
  recommendedLetterNo: "",
  boothName: "",
  boothNo: "",
  panchayatName: "",
  village: "",
  majraFaliya: "",
  workProblem: "",
  office: "",
  approximateCost: 0,
  department: "",
  priority: "",
  tsNoDate: "",
  asNoDate: "",
  typeOfWork: "",
  subWorkType: "",
  middleMen: "",
  middleManContact: "",
  beneficiaryName: "",
  beneficiaryContact: "",
  po: "",
  avedanFile: "",
  avedanFileName: "",
  accountDetails: "",
  adharCardNumber: "",
  ifscNumber: "",
  documentFile: "",
  documentFileName: "",
  remarkGoshana: "",
  remarkTipUsd: "",
  addedBy: "",
  latLng: "",
  registrationDate: "",
  totalMembers: 0,
  status: "Pending",
  issueType: "assembly-issue",
};
